# This script provides all initial merging and renaming steps to get one cohesive dataframe for future analysis

# 1. Load data and modules

In [7]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
# Create path
path = r'/Users/tyrasmussen/Desktop/FVTC/Spring 2026/Data Analytics Capstone/MM/MM Data/2002 - 2025/Data'

# Part 1 02-25 Dataset

In [9]:
# Load KenPom Defense

kp_def = pd.read_csv(os.path.join(path, 'INT _ KenPom _ Defense.csv'))
kp_eff = pd.read_csv(os.path.join(path, 'INT _ KenPom _ Efficiency.csv'))
kp_hei = pd.read_csv(os.path.join(path, 'INT _ KenPom _ Height.csv'))
kp_mis = pd.read_csv(os.path.join(path, 'INT _ KenPom _ Miscellaneous Team Stats.csv'))
kp_off = pd.read_csv(os.path.join(path, 'INT _ KenPom _ Offense.csv'))
kp_pointdis = pd.read_csv(os.path.join(path, 'INT _ KenPom _ Point Distribution.csv'))
kp_sumpre = pd.read_csv(os.path.join(path, 'INT _ KenPom _ Summary (Pre-Tournament).csv'))
kp_sum = pd.read_csv(os.path.join(path, 'INT _ KenPom _ Summary.csv'))
ref_coach = pd.read_csv(os.path.join(path, 'REF _ Current NCAAM Coaches (2025).csv'))
ref_conf = pd.read_csv(os.path.join(path, 'REF _ NCAAM Conference and ESPN Team Name Mapping.csv'))
ref_tour_teams = pd.read_csv(os.path.join(path, 'REF _ Post-Season Tournament Teams.csv'))
ref_top12_week6 = pd.read_csv(os.path.join(path, 'REF _ Top 12 in AP Top 25 During Week 6.csv'))

# 2. Rename and merge relevant columns

In [10]:
# KP def minimum year
min_year = kp_def['Season'].min()
print(f'Minimum Year in KenPom Defense Data: {min_year}')

Minimum Year in KenPom Defense Data: 1999

In [11]:
kp_def.head()

,Season,TeamName,eFGPct,RankeFGPct,TOPct,RankTOPct,ORPct,RankORPct,FTRate,RankFTRate
0,2023,Abilene Christian,56.539611,359,23.340150,12,28.645833,190,45.590433,358
1,2023,Air Force,49.301513,115,17.084787,241,28.557505,182,35.157159,276
2,2023,Akron,49.716070,129,17.772788,192,26.534466,88,28.052243,95
3,2023,Alabama,41.307080,1,15.828368,312,27.901235,151,32.635107,221
4,2023,Alabama A&M,49.427366,117,21.366813,32,33.918129,350,41.772152,345

In [12]:
kp_off.head()

,Season,TeamName,eFGPct,RankeFGPct,TOPct,RankTOPct,ORPct,RankORPct,FTRate,RankFTRate
0,2025,Abilene Christian,46.689148,332,20.740433,350,30.069238,178,37.155120,57
1,2025,Air Force,50.092822,220,20.721288,348,22.736031,343,35.396040,108
2,2025,Akron,54.940898,34,16.354727,131,32.179054,108,26.950355,332
3,2025,Alabama,56.600590,10,16.559930,142,33.725202,64,39.308309,30
4,2025,Alabama A&M,45.098039,353,21.938360,360,33.911535,57,38.581315,37

In [13]:
# Rename offensive columns to _off
kp_off = kp_off.add_suffix('_off')

In [14]:
# Rename defensive columns to _def
kp_def = kp_def.add_suffix('_def')

In [15]:
# Change season_def and TeamName_def to season and TeamName for merging
kp_def = kp_def.rename(columns={'Season_def': 'Season', 'TeamName_def': 'TeamName'})
kp_off = kp_off.rename(columns={'Season_off': 'Season', 'TeamName_off': 'TeamName'})

In [16]:
kp_off.head()

,Season,TeamName,eFGPct_off,RankeFGPct_off,TOPct_off,RankTOPct_off,ORPct_off,RankORPct_off,FTRate_off,RankFTRate_off
0,2025,Abilene Christian,46.689148,332,20.740433,350,30.069238,178,37.155120,57
1,2025,Air Force,50.092822,220,20.721288,348,22.736031,343,35.396040,108
2,2025,Akron,54.940898,34,16.354727,131,32.179054,108,26.950355,332
3,2025,Alabama,56.600590,10,16.559930,142,33.725202,64,39.308309,30
4,2025,Alabama A&M,45.098039,353,21.938360,360,33.911535,57,38.581315,37

In [17]:
kp_def.head()

,Season,TeamName,eFGPct_def,RankeFGPct_def,TOPct_def,RankTOPct_def,ORPct_def,RankORPct_def,FTRate_def,RankFTRate_def
0,2023,Abilene Christian,56.539611,359,23.340150,12,28.645833,190,45.590433,358
1,2023,Air Force,49.301513,115,17.084787,241,28.557505,182,35.157159,276
2,2023,Akron,49.716070,129,17.772788,192,26.534466,88,28.052243,95
3,2023,Alabama,41.307080,1,15.828368,312,27.901235,151,32.635107,221
4,2023,Alabama A&M,49.427366,117,21.366813,32,33.918129,350,41.772152,345

## Merge all data from 2002-2025 dataset into one

In [18]:
# Merge dataframes
full_df = pd.merge(
kp_off,
kp_def,
on=['Season', 'TeamName'],
how='outer'
)

In [19]:
full_df.head()

,Season,TeamName,eFGPct_off,RankeFGPct_off,TOPct_off,RankTOPct_off,ORPct_off,RankORPct_off,FTRate_off,RankFTRate_off,eFGPct_def,RankeFGPct_def,TOPct_def,RankTOPct_def,ORPct_def,RankORPct_def,FTRate_def,RankFTRate_def
0,2025,Abilene Christian,46.689148,332,20.740433,350,30.069238,178,37.155120,57,51.411290,211,24.010102,1,31.450720,263,51.276882,364
1,2025,Air Force,50.092822,220,20.721288,348,22.736031,343,35.396040,108,54.635950,334,15.684864,279,29.064039,142,35.437998,242
2,2025,Akron,54.940898,34,16.354727,131,32.179054,108,26.950355,332,50.073783,134,17.270259,167,29.474548,161,33.054599,184
3,2025,Alabama,56.600590,10,16.559930,142,33.725202,64,39.308309,30,47.820055,49,13.488046,351,29.426752,159,33.174792,187
4,2025,Alabama A&M,45.098039,353,21.938360,360,33.911535,57,38.581315,37,54.301403,327,20.994775,21,34.647303,350,46.674802,359

In [20]:
kp_eff.head()

,Season,Team,Conference,Adjusted Temo,Adjusted Tempo Rank,Raw Tempo,Raw Tempo Rank,Adjusted Offensive Efficiency,Adjusted Offensive Efficiency Rank,Raw Offensive Efficiency,Raw Offensive Efficiency Rank,Adjusted Defensive Efficiency,Adjusted Defensive Efficiency Rank,Raw Defensive Efficiency,Raw Defensive Efficiency Rank,Avg Possession Length (Offense),Avg Possession Length (Offense) Rank,Avg Possession Length (Defense),Avg Possession Length (Defense) Rank
0,2010,Air Force,MWC,57.3,346,59.4,344,96.8,265,93.6,296,105.5,229,106.0,285,22.0,345.0,18.3,269.0
1,2010,Akron,MAC,65.1,214,66.3,231,105.3,141,104.4,104,100.1,116,98.1,96,18.4,242.0,18.0,212.0
2,2010,Alabama,SEC,64.2,247,66.0,240,107.9,88,103.8,120,95.3,53,97.9,94,18.5,247.0,18.0,213.0
3,2010,Alabama A&M,SWAC,70.2,25,72.5,20,87.5,338,87.8,335,107.2,264,96.5,65,16.7,72.0,16.4,11.0
4,2010,Alabama St.,SWAC,65.2,212,67.9,145,93.5,298,93.8,295,106.2,242,97.0,76,18.7,268.0,16.9,43.0

In [21]:
# Rename kp_eff Team to TeamName for merging
kp_eff = kp_eff.rename(columns={'Team': 'TeamName'})

In [22]:
kp_hei.head()

,Season,TeamName,AvgHeight,RankAvgHeight,CenterHeight,RankCenterHeight,PFHeight,RankPFHeight,SFHeight,RankSFHeight,...,CenterDR,RankCenterDR,PFDR,RankPFDR,SFDR,RankSFDR,SGDR,RankSGDR,PGDR,RankPGDR
0,2019,Abilene Christian,75.89,299,-0.87,271,-0.71,260,-0.93,295,...,24.34,228,23.10,220,18.34,203,18.71,70,15.46,104
1,2019,Air Force,77.15,126,-2.01,340,0.19,145,0.33,113,...,22.00,292,23.29,216,21.18,89,19.24,61,14.24,150
2,2019,Akron,76.31,249,0.27,128,-0.96,287,0.20,125,...,23.66,253,20.90,277,22.85,52,19.29,58,13.23,211
3,2019,Alabama,77.88,39,-0.01,161,0.69,97,1.08,65,...,25.70,190,23.75,198,19.68,144,19.72,46,11.09,312
4,2019,Alabama A&M,75.77,313,-1.47,322,-0.55,240,-0.04,174,...,25.10,208,22.03,243,19.85,134,18.71,71,14.25,148

In [23]:
kp_mis.head()

,Season,TeamName,FG2Pct,RankFG2Pct,FG3Pct,RankFG3Pct,FTPct,RankFTPct,BlockPct,RankBlockPct,...,RankOppARate,StlRate,RankStlRate,OppStlRate,RankOppStlRate,DFP,NSTRate,RankNSTRate,OppNSTRate,RankOppNSTRate
0,2015,Abilene Christian,42.0106,338,37.8026,43,72.7924,55,3.4519,348,...,139,0.0914,182,0.0903,137,NaN,NaN,NaN,NaN,NaN
1,2015,Air Force,53.8983,12,35.4344,114,65.8590,289,6.9597,286,...,344,0.1031,88,0.0946,191,NaN,NaN,NaN,NaN,NaN
2,2015,Akron,46.7000,219,34.9345,141,66.0000,286,12.1212,61,...,56,0.0966,143,0.1075,303,NaN,NaN,NaN,NaN,NaN
3,2015,Alabama,52.2750,33,32.2009,258,71.8407,89,10.8756,106,...,225,0.0985,123,0.0793,39,NaN,NaN,NaN,NaN,NaN
4,2015,Alabama A&M,45.4348,276,29.0614,338,64.7635,315,6.1281,317,...,54,0.0873,225,0.1078,305,NaN,NaN,NaN,NaN,NaN

In [24]:
kp_pointdis.head()

,Season,TeamName,OffFT,RankOffFT,Off2PtFG,RankOff2PtFG,Off3PtFG,RankOff3PtFG,DefFT,RankDefFT,Def2PtFG,RankDef2PtFG,Def3PtFG,RankDef3PtFG
0,1999,Air Force,24.8,19,39.2,315,36.1,10,24.1,42,54.3,133,21.6,277
1,1999,Akron,25.4,5,50.3,240,24.3,185,18.1,270,57.7,37,24.3,200
2,1999,Alabama,20.8,155,60.4,25,18.8,289,21.5,123,50.9,244,27.6,86
3,1999,Alabama A&M,23.0,65,48.9,259,28.1,86,22.1,92,57.0,56,20.9,287
4,1999,Alabama St.,24.9,16,54.0,147,21.1,258,20.6,171,54.7,119,24.7,185

In [25]:
kp_sumpre.head()

,Season,TeamName,Tempo,RankTempo,AdjTempo,RankAdjTempo,OE,RankOE,AdjOE,RankAdjOE,DE,RankDE,AdjDE,RankAdjDE,AdjEM,RankAdjEM,Seed
0,2007,North Carolina,74.1408,10,71.8899,8,115.960,2,120.450,3,91.7164,10,88.7132,2,31.7371,1,1.0
1,2007,Ohio St.,65.1235,235,64.2281,208,113.242,14,119.341,6,92.5033,13,90.4737,10,28.8677,2,1.0
2,2007,Florida,67.2672,150,64.9276,179,117.548,1,120.927,2,91.3624,7,92.0656,14,28.8619,3,1.0
3,2007,Kansas,69.5468,78,68.0793,66,111.497,26,115.098,29,86.5831,1,86.8370,1,28.2605,4,1.0
4,2007,Georgetown,59.6996,328,59.1413,326,115.392,5,121.238,1,95.4232,38,93.1473,19,28.0911,5,2.0

In [26]:
kp_sum.head()

,Season,TeamName,Tempo,RankTempo,AdjTempo,RankAdjTempo,OE,RankOE,AdjOE,RankAdjOE,DE,RankDE,AdjDE,RankAdjDE,AdjEM,RankAdjEM
0,2020,Abilene Christian,70.4017,105,68.4092,172,101.4500,159,99.0562,239,96.1085,67,100.1980,126,-1.14144,184
1,2020,Air Force,68.9032,183,68.7757,147,104.9150,89,107.7850,76,109.9970,332,110.2730,316,-2.48752,197
2,2020,Akron,70.1211,118,69.4330,110,106.7760,58,108.4760,66,95.6119,57,98.9396,103,9.53601,82
3,2020,Alabama,76.0855,4,74.7606,4,105.9970,71,110.9690,37,102.1720,221,99.4710,114,11.49840,60
4,2020,Alabama A&M,69.6460,137,67.7433,213,88.2169,347,87.9342,348,101.9150,216,108.1540,297,-20.21960,343

In [27]:
# Merge all KenPom dataframes into one
full_kenpom_df = full_df.copy()
dataframes = [kp_eff, kp_hei, kp_mis, kp_pointdis, kp_sumpre, kp_sum]
for df in dataframes:
    # Rename columns to avoid conflicts
    df_renamed = df.add_suffix('_extra')
    df_renamed = df_renamed.rename(columns={'Season_extra': 'Season', 'TeamName_extra': 'TeamName'})
    
    # Merge with the full_kenpom_df
    full_kenpom_df = pd.merge(
        full_kenpom_df,
        df_renamed,
        on=['Season', 'TeamName'],
        how='outer'
    )
full_kenpom_df.head()

,Season,TeamName,eFGPct_off,RankeFGPct_off,TOPct_off,RankTOPct_off,ORPct_off,RankORPct_off,FTRate_off,RankFTRate_off,...,OE_extra_y,RankOE_extra_y,AdjOE_extra_y,RankAdjOE_extra_y,DE_extra_y,RankDE_extra_y,AdjDE_extra_y,RankAdjDE_extra_y,AdjEM_extra_y,RankAdjEM_extra_y
0,2025,Abilene Christian,46.689148,332.0,20.740433,350.0,30.069238,178.0,37.155120,57.0,...,95.6706,346.0,97.6737,330.0,100.773,54.0,102.3350,92.0,-4.66102,221.0
1,2025,Air Force,50.092822,220.0,20.721288,348.0,22.736031,343.0,35.396040,108.0,...,95.3082,347.0,98.9098,312.0,113.105,335.0,111.6740,272.0,-12.76410,310.0
2,2025,Akron,54.940898,34.0,16.354727,131.0,32.179054,108.0,26.950355,332.0,...,114.8680,29.0,113.5550,71.0,105.141,154.0,107.0810,182.0,6.47358,100.0
3,2025,Alabama,56.600590,10.0,16.559930,142.0,33.725202,64.0,39.308309,30.0,...,118.4340,9.0,126.8140,4.0,106.226,175.0,96.4694,28.0,30.34500,6.0
4,2025,Alabama A&M,45.098039,353.0,21.938360,360.0,33.911535,57.0,38.581315,37.0,...,94.8255,352.0,92.2313,361.0,109.965,274.0,115.5890,334.0,-23.35810,360.0

### # Merge REF Post season and Top 12 dataframes

In [28]:
ref_tour_teams.head()

,Season,Team Name,Seed,Region,Post-Season Tournament,Post-Season Tournament Sorting Index,Vulnerable Top 2 Seed?,Tournament Winner?,Tournament Championship?,Final Four?
0,2025,Auburn,1,South,March Madness,1,No,NaN,NaN,NaN
1,2025,Alabama State,16,South,March Madness,1,NaN,NaN,NaN,NaN
2,2025,St. Francis (PA),16,South,March Madness,1,NaN,NaN,NaN,NaN
3,2025,Louisville,8,South,March Madness,1,NaN,NaN,NaN,NaN
4,2025,Creighton,9,South,March Madness,1,NaN,NaN,NaN,NaN

In [29]:
# Rename Team Name to TeamName for merging
ref_tour_teams = ref_tour_teams.rename(columns={'Team Name': 'TeamName'})

In [30]:
ref_top12_week6.head()

   Season Mapped ESPN Team Name Top 12 in AP Top 25 During Week 6?
0    2025             Tennessee                                Yes
1    2025                Auburn                                Yes
2    2025            Iowa State                                Yes
3    2025                  Duke                                Yes
4    2025              Kentucky                                Yes

In [31]:
# Rename Mapped ESPN Team Name to TeamName for merging
ref_top12_week6 = ref_top12_week6.rename(columns={'Mapped ESPN Team Name': 'TeamName'})

In [32]:
# Add two ref tables to full_kenpom_df
ref_dataframes = [ref_tour_teams, ref_top12_week6]
for ref_df in ref_dataframes:
    # Rename columns to avoid conflicts
    ref_df_renamed = ref_df.add_suffix('_ref')
    ref_df_renamed = ref_df_renamed.rename(columns={'Season_ref': 'Season', 'TeamName_ref': 'TeamName'})
    
    # Merge with the full_kenpom_df
    full_kenpom_df = pd.merge(
        full_kenpom_df,
        ref_df_renamed,
        on=['Season', 'TeamName'],
        how='outer'
    )

In [33]:
# Check ref_conf table for column name
ref_conf.head()

  Conference   TeamName         Mapped Conference Name Mapped ESPN Team Name
0        A10     Butler  Atlantic 10 Conference (A-10)                Butler
1        A10  Charlotte  Atlantic 10 Conference (A-10)             Charlotte
2        A10   Davidson  Atlantic 10 Conference (A-10)              Davidson
3        A10     Dayton  Atlantic 10 Conference (A-10)                Dayton
4        A10   Duquesne  Atlantic 10 Conference (A-10)              Duquesne

In [34]:
# Add conference columns
full_kenpom_df = pd.merge(
    full_kenpom_df,
    ref_conf,
    on='TeamName',
    how='left'
)

In [35]:
# Check new dataframe that includes all data for 2002-2025 seasons
full_kenpom_df.head()

,Season,TeamName,eFGPct_off,RankeFGPct_off,TOPct_off,RankTOPct_off,ORPct_off,RankORPct_off,FTRate_off,RankFTRate_off,...,Post-Season Tournament_ref,Post-Season Tournament Sorting Index_ref,Vulnerable Top 2 Seed?_ref,Tournament Winner?_ref,Tournament Championship?_ref,Final Four?_ref,Top 12 in AP Top 25 During Week 6?_ref,Conference,Mapped Conference Name,Mapped ESPN Team Name
0,2025,Abilene Christian,46.689148,332.0,20.740433,350.0,30.069238,178.0,37.155120,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Slnd,Southland Conference (SLC),Abilene Christian
1,2025,Abilene Christian,46.689148,332.0,20.740433,350.0,30.069238,178.0,37.155120,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WAC,Western Athletic Conference (WAC),Abilene Christian
2,2025,Air Force,50.092822,220.0,20.721288,348.0,22.736031,343.0,35.396040,108.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MWC,Mountain West Conference (MW),Air Force
3,2025,Akron,54.940898,34.0,16.354727,131.0,32.179054,108.0,26.950355,332.0,...,March Madness,1.0,NaN,NaN,NaN,NaN,NaN,MAC,Mid-American Conference (MAC),Akron
4,2025,Alabama,56.600590,10.0,16.559930,142.0,33.725202,64.0,39.308309,30.0,...,March Madness,1.0,No,NaN,NaN,NaN,Yes,SEC,Southeastern Conference (SEC),Alabama

In [36]:
# Print shape of final dataframe
full_kenpom_df.shape

(16205, 169)

## Part 1 Final Dataframe name: 'full_kenpom_df'

### Export part 1 dataframe

In [51]:
# Path
path = r'/Users/tyrasmussen/Desktop/FVTC/Spring 2026/Data Analytics Capstone/MM/MM Data/Merged'

In [52]:
# Save final dataframe to CSV
full_kenpom_df.to_csv(os.path.join(path, 'FINAL _ Merged KenPom and Reference Data.csv'), index=False)

# Part 2 08-25 Dataset

In [38]:
# Create path
path = r'/Users/tyrasmussen/Desktop/FVTC/Spring 2026/Data Analytics Capstone/MM/MM Data/2008 - 2025/Data'

In [42]:
# Load all datasets
df_538 = pd.read_csv(os.path.join(path, '538 Ratings.csv'))
ap_week6 = pd.read_csv(os.path.join(path, 'AP Poll Week 6.csv'))
bart_away_neutral = pd.read_csv(os.path.join(path, 'Barttorvik Away-Neutral.csv'))
bart_away = pd.read_csv(os.path.join(path, 'Barttorvik Away.csv'))
bart_home = pd.read_csv(os.path.join(path, 'Barttorvik Home.csv'))
bart_neutral = pd.read_csv(os.path.join(path, 'Barttorvik Neutral.csv'))
coach_results = pd.read_csv(os.path.join(path, 'Coach Results.csv'))
conf_results = pd.read_csv(os.path.join(path, 'Conference Results.csv'))
conf_stats_away_neutral = pd.read_csv(os.path.join(path, 'Conference Stats Away Neutral.csv'))
conf_stats_away = pd.read_csv(os.path.join(path, 'Conference Stats Away.csv'))
conf_stats_home = pd.read_csv(os.path.join(path, 'Conference Stats Home.csv'))
conf_stats_neutral = pd.read_csv(os.path.join(path, 'Conference Stats Neutral.csv'))
conf_stats = pd.read_csv(os.path.join(path, 'Conference Stats.csv'))
evan_miya = pd.read_csv(os.path.join(path, 'EvanMiya.csv'))
heat_check_ratings = pd.read_csv(os.path.join(path, 'Heat Check Ratings.csv'))
heat_check_tournament = pd.read_csv(os.path.join(path, 'Heat Check Tournament Index.csv'))
kp_bart = pd.read_csv(os.path.join(path, 'KenPom Barttorvik.csv'))
kp_pre = pd.read_csv(os.path.join(path, 'KenPom Preseason.csv'))
preseason_votes = pd.read_csv(os.path.join(path, 'Preseason Votes.csv'))
public_picks = pd.read_csv(os.path.join(path, 'Public Picks.csv'))
resumes = pd.read_csv(os.path.join(path, 'Resumes.csv'))
seed_results = pd.read_csv(os.path.join(path, 'Seed Results.csv'))
shooting_splits = pd.read_csv(os.path.join(path, 'Shooting Splits.csv'))
team_results = pd.read_csv(os.path.join(path, 'Team Results.csv'))
team_rankings_away = pd.read_csv(os.path.join(path, 'TeamRankings Away.csv'))
team_rankings_home = pd.read_csv(os.path.join(path, 'TeamRankings Home.csv'))
team_rankings_neutral = pd.read_csv(os.path.join(path, 'TeamRankings Neutral.csv'))
team_rankings = pd.read_csv(os.path.join(path, 'TeamRankings.csv'))
tourn_locations = pd.read_csv(os.path.join(path, 'Tournament Locations.csv'))
tourn_matchups = pd.read_csv(os.path.join(path, 'Tournament Matchups.csv'))
tourn_sim = pd.read_csv(os.path.join(path, 'Tournament Simulation.csv'))
upset_count = pd.read_csv(os.path.join(path, 'Upset Count.csv'))
upset_seed_info = pd.read_csv(os.path.join(path, 'Upset Seed Info.csv'))
z_rating = pd.read_csv(os.path.join(path, 'Z Rating.csv'))

In [47]:
# Create entire new dataframe for part 2 merges

# List of dataframes to merge (only ones with team data)

team_master = evan_miya.copy()
team_dataframes = [
    df_538,
    ap_week6,
    bart_away_neutral,
    bart_away,
    bart_home,
    bart_neutral,
    heat_check_ratings,
    heat_check_tournament,
    kp_bart,
    kp_pre,
    preseason_votes,
    public_picks,
    resumes,
    shooting_splits,
    team_rankings_away,
    team_rankings_home,
    team_rankings_neutral,
    team_rankings,
    tourn_locations,
    tourn_matchups,
    tourn_sim,
    z_rating
]
for team_df in team_dataframes:
    # Rename columns to avoid conflicts
    team_df_renamed = team_df.add_suffix('_part2')
    team_df_renamed = team_df_renamed.rename(columns={'TEAM NO_part2': 'TEAM NO'})
    
    # Merge with the team_master
    team_master = pd.merge(
        team_master,
        team_df_renamed,
        on=['TEAM NO'],
        how='outer'
    )

/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROUND_part2_x', 'TEAM_part2_x', 'SEED_part2_x', 'YEAR_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'BADJ EM RANK_part2_x', 'YEAR_part2_x', 'EFF HGT_part2_x', 'BADJ O_part2_x', 'OP FT%_part2_x', 'BLKED% RANK_part2_x', 'BARTHAG_part2_x', 'PPPO RANK_part2_x', 'RAW T RANK_part2_x', 'FTR RANK_part2_x', '2PT%D_part2_x', 'BADJ EM_part2_x', 'BADJ D RANK_part2_x', 'OP OREB% RANK_part2_x', '3PTRD_part2_x', 'OREB% RANK_part2_x', 'ROUND_part2_x', 'TALENT_part2_x', '3PTR RANK_part2_x', 'EFF HGT RANK_part2_x', 'BADJ O RANK_part2_x', 'AVG HGT RANK_part2_x', '2PTRD_part2_x', 'OP OREB%_part2_x', 'TALENT RANK_part2_x', 'GAMES_part2_x', 'BLKED%_part2_x', 'OP DREB% RANK_part2_x', 'FTR_part2_x', 'PPPO_part2_x', 'FTRD_part2_x', 'BADJ T_part2_x', 'TEAM_part2_x', 'OP DREB%_part2_x', '2PT%D RANK_part2_x', 'TOV%D_part2_x', 'DREB%_part2_x', 'TOV%D RANK_part2_x', 'OP AST%_part2_x', 'AST%_part2_x', 'BADJT RANK_part2_x', 'WIN%_part2_x', 'EXP_part2_x', 'DREB% RANK_part2_x', 'BARTHAG RANK_part2_x', 'OP FT% RANK_part2_x', '3PTR_part2_x', 'EFG%D_part2_x', '2PTRD RANK_part2_x', 'EXP RANK_part2_x', '3PT% RANK_part2_x', 'SEED_part2_x', 'EFG%_part2_x', '3PTRD RANK_part2_x', 'FT%_part2_x', '3PT%D_part2_x', 'RAW T_part2_x', '2PT% RANK_part2_x', '3PT%D RANK_part2_x', 'OREB%_part2_x', 'TOV% RANK_part2_x', 'TOV%_part2_x', 'EFGD% RANK_part2_x', 'EFG% RANK_part2_x', 'W_part2_x', 'WAB_part2_x', 'ELITE SOS_part2_x', '3PT%_part2_x', 'L_part2_x', '2PTR_part2_x', 'FTRD RANK_part2_x', 'ELITE SOS RANK_part2_x', 'BLK% RANK_part2_x', 'FT% RANK_part2_x', 'PPPD RANK_part2_x', 'AVG HGT_part2_x', 'BADJ D_part2_x', 'PPPD_part2_x', 'BLK%_part2_x', 'AST% RANK_part2_x', 'TEAM ID_part2_x', '2PT%_part2_x', 'OP AST% RANK_part2_x', '2PTR RANK_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROUND_part2_x', 'TEAM_part2_x', 'SEED_part2_x', 'YEAR_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROUND_part2_x', 'TEAM_part2_x', 'SEED_part2_x', 'YEAR_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'TEAM_part2_x', 'YEAR_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROUND_part2_x', 'SEED_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'TEAM_part2_x', 'YEAR_part2_x', 'TEAM ID_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROUND_part2_x', 'TEAM_part2_x', 'SEED_part2_x', 'YEAR_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'TR RANK_part2_x', 'YEAR_part2_x', 'LO_part2_x', 'V 1-25 WINS_part2_x', 'TEAM_part2_x', 'V 51-100 LOSS_part2_x', 'TR RATING_part2_x', 'ROUND_part2_x', 'LAST_part2_x', 'HI_part2_x', 'V 26-50 WINS_part2_x', 'V 1-25 LOSS_part2_x', 'V 51-100 WINS_part2_x', 'SEED_part2_x', 'V 26-50 LOSS_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROUND_part2_x', 'TEAM_part2_x', 'SEED_part2_x', 'YEAR_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(
/var/folders/l9/n_0jq3zj66l9v7k98dd7cpqc0000gn/T/ipykernel_54281/2952448626.py:36: FutureWarning: Passing 'suffixes' which cause duplicate columns {'ROUND_part2_x', 'TEAM_part2_x', 'SEED_part2_x', 'YEAR_part2_x'} in the result is deprecated and will raise a MergeError in a future version.
  team_master = pd.merge(

In [48]:
team_master.head()

,YEAR,TEAM NO,TEAM,SEED,ROUND,O RATE,D RATE,RELATIVE RATING,OPPONENT ADJUST,PACE ADJUST,...,TEAM_part2_x,SEED_part2_x,ROUND_part2_x,CURRENT ROUND_part2_y,YEAR_part2_y,TEAM_part2_y,SEED_part2_y,ROUND_part2_y,Z RATING_part2,Z RATING RANK_part2
0,2025.0,1147.0,Akron,13.0,0.0,6.277529,0.567429,6.844958,4.509381,1.703296,...,Akron,13.0,64.0,64.0,2025.0,Akron,13.0,0.0,10.16,53.0
1,2025.0,1146.0,Alabama,2.0,0.0,18.629272,9.390035,28.019306,22.860154,-27.885430,...,Alabama,2.0,1.0,64.0,2025.0,Alabama,2.0,0.0,15.62,11.0
2,2025.0,1146.0,Alabama,2.0,0.0,18.629272,9.390035,28.019306,22.860154,-27.885430,...,Alabama,2.0,1.0,64.0,2025.0,Alabama,2.0,0.0,15.62,11.0
3,2025.0,1146.0,Alabama,2.0,0.0,18.629272,9.390035,28.019306,22.860154,-27.885430,...,Alabama,2.0,1.0,64.0,2025.0,Alabama,2.0,0.0,15.62,11.0
4,2025.0,1146.0,Alabama,2.0,0.0,18.629272,9.390035,28.019306,22.860154,-27.885430,...,Alabama,2.0,1.0,64.0,2025.0,Alabama,2.0,0.0,15.62,11.0

## Part 2 Final Dataframe: 'team_master'

# Export part 2 dataframe

In [ ]:
# Path
path = r'/Users/tyrasmussen/Desktop/FVTC/Spring 2026/Data Analytics Capstone/MM/MM Data/Merged'

In [55]:
# Save final dataframe to CSV
team_master.to_csv(os.path.join(path, 'FINAL_Team_Master_2008_2025.csv'), index=False)